markdown: redcarpet
name: How to test and measure content
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: introduction/
  internal: true
- text: Reading ease scores
  url: reading-ease-scores/
  internal: true
- text: Cloze test
  url: cloze-test/
  internal: true
- text: A/B test
  url: a-b-test/
  internal: true
- text: Test your knowledge
  url: test-your-knowledge/
  internal: true
- text: Additional resources
  url: additional-resources/
  internal: true

repos:
- name: Edu measure content
  description: Main repository
  url: https://github.com/18F/edu-measure-content

back_link:
  url: "https://pages.18f.gov/edu/"
  text: Return to 18F Edu

google_analytics_ua: UA-48605964-19

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"
